### ISSUE TITLE
RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by SytanSD** [LAION-AI/natural_voice_assistant#14]
Environment:
Windows 10 Pro - 10.0.19045 Build 19045
Python - 3.10.12 (as requested)
Conda Version - 23.5.2

Steps for Reproduction:
After full installation as directed, I tried to run [python main.py]
At this point, I get an error stating that eSpeak is not installed

Expected Behavior:
BUD-E should boot and function for conversation

Actual Behavior:
Traceback (most recent call last):
  File "E:\BUD-E\natural_voice_assistant\main.py", line 175, in <module>
    main()
  File "E:\BUD-E\natural_voice_assistant\main.py", line 169, in main
    model = STT_LLM_TTS(device=device)
  File "E:\BUD-E\natural_voice_assistant\stt_llm_tts_model.py", line 371, in __init__
    self.tts = TTS(device=device)
  File "E:\BUD-E\natural_voice_assistant\stt_llm_tts_model.py", line 333, in __init__
    self.tts_model = StyleTTS2Model(device=device)
  File "E:\BUD-E\natural_voice_assistant\style_tts2_model.py", line 38, in __init__
    self.global_phonemizer = phonemizer.backend.EspeakBackend(language='en-us', preserve_punctuation=True,  with_stress=True)
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\phonemizer\backend\espeak\espeak.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\phonemizer\backend\espeak\base.py", line 39, in __init__
    super().__init__(
  File "C:\Users\Sytan\miniconda3\envs\bud_e\lib\site-packages\phonemizer\backend\base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system

Additional Notes:
The command provided to run is as follows: conda env config vars set PHONEMIZER_ESPEAK_LIBRARY="C:\Program Files\eSpeak NG\libespeak-ng.dll", however, I found that SpeakE was installed at dir: C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll. After fixing this and pointing to the right file dir, I am still getting the same issue stating that I do not have SpeakE installed. I made sure to use the command as stated, and additionally restarted my conda env after pointing it.

**Comment by SytanSD** [comment]
SOLUTION: I made the mistake of installing the x86 version of eSpeak for some reason. Fixing this solved the issue.
