### ISSUE TITLE
OSError: [Errno -9999] Unanticipated host error pyaudio if you deny access to microphone in windows settings

### ISSUE THREAD

**Issue by twobob** [LAION-AI/natural_voice_assistant#18]
The system will report OSError: [Errno -9999] Unanticipated host error pyaudio if you deny access to microphone in windows settings

And close out

`Currently input device with id 1 is used for recording. To change the audio device, please use the --audio-device-idx parameter.

Traceback (most recent call last):
  File "d:\repo\natural_voice_assistant\main.py", line 306, in <module>
    main()
  File "d:\repo\natural_voice_assistant\main.py", line 296, in main
    record(audio, sample_rate, audio_channels, audio_input_buffer, start_recording, args.audio_device_idx, args.audio_details)
  File "d:\repo\natural_voice_assistant\main.py", line 115, in record
    streamIn = audio.open(format=pyaudio.paFloat32, channels=channels,
  File "C:\webui\installer_files\conda\envs\bud_e\lib\site-packages\pyaudio\__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "C:\webui\installer_files\conda\envs\bud_e\lib\site-packages\pyaudio\__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9999] Unanticipated host error`

Not really a bug but perhaps add it to the install notes.

![image](https://github.com/LAION-AI/natural_voice_assistant/assets/915232/3ffbb7bd-3228-41ea-890c-b38c1ff5b716)

**Comment by braunale** [comment]
Hey @twobob, thanks for pointing this out. I've added a troubleshooting section in the readme and included a hint regarding microphone access.
