### ISSUE TITLE
The directory is not found 

### ISSUE THREAD

**Issue by twobob** [LAION-AI/natural_voice_assistant#19]
>  ## Listening...
>  what
>  is
>  the
>  cap
> ital
>  of
>  france

## Total Latency:  0.939
```
Process Process-2:
Traceback (most recent call last):
  File "C:\webui\installer_files\conda\envs\bud_e\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\webui\installer_files\conda\envs\bud_e\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\repo\natural_voice_assistant\main.py", line 228, in main_loop
    text, wav, interrupt = model(chunk_audio, chunk_lengths)
  File "C:\webui\installer_files\conda\envs\bud_e\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\webui\installer_files\conda\envs\bud_e\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\repo\natural_voice_assistant\models_voice_assistant\stt_llm_tts_model.py", line 699, in forward
    end, response, wav = self.handle_stop_conditions()
  File "d:\repo\natural_voice_assistant\models_voice_assistant\stt_llm_tts_model.py", line 562, in handle_stop_conditions
    with open('latencies/times_stt', 'w') as fout:
FileNotFoundError: [Errno 2] No such file or directory: 'latencies/times_stt'
```

If I make it manually it works fine, perhaps consider a placeholder in the git? :)

**Comment by twobob** [comment]
For Furture readers: to be clear I made the **latencies** folder to fix this in the main directory
