### ISSUE TITLE
Raised Error Related Models 

### ISSUE THREAD

**Issue by y3rawat** [LAION-AI/natural_voice_assistant#24]
python main.py
Traceback (most recent call last):
  File "/home/y3/Desktop/try/p/bin/natural_voice_assistant/main.py", line 13, in <module>
    from models_voice_assistant.stt_llm_tts_model import STT_LLM_TTS
  File "/home/y3/Desktop/try/p/bin/natural_voice_assistant/models_voice_assistant/stt_llm_tts_model.py", line 6, in <module>
    from models_voice_assistant.TTS.style_tts2_model import StyleTTS2Model
  File "/home/y3/Desktop/try/p/bin/natural_voice_assistant/models_voice_assistant/TTS/style_tts2_model.py", line 11, in <module>
    from models import *
ModuleNotFoundError: No module named 'models'

**Comment by braunale** [comment]
Hey @y3-rawat, did you cloned the repo with the **recurse-submodules** argument? So: 
**git clone --recurse-submodules https://github.com/LAION-AI/natural_voice_assistant.git**
The voice assistant requires the StyleTTS2 repo to be cloned as well and this is handled by passing this argument.
